environment:
  seed: 0
  timeout: 300
  end_criterion: failure
  obs_type: perfect

agent:
  agent_id: ego
  dyn: Dubins6D
  footprint: Box
  verbose: false
  gui: false
  gui_imaginary: false
  dt: 0.05  # time step
  # Environment parameters
  goalR: 0.25  # collision radius
  state_max_x: 3.0  # bounds for state space
  state_max_y: 2.0  # bounds for state space
  state_box_limit: [-3.0, 3.0, -2.0, 2.0]  # will be overridden by state_max in environment
  # Action ranges - Continuous control
  action_range: 
    ctrl: &ctrl_range
      - [-1.9, 1.9]  # omega_e (evader turn rate) - continuous actions
    dstb: &dstb_range
      - [-1.9, 1.9]  # omega_p (pursuer turn rate) - continuous actions
  action_type: center_sampling
  action_center:
    - 0.0  # center of discrete actions
  # Dubins dynamics parameters
  evader_velocity: 0.6
  pursuer_velocity: 0.6
  omega_e_max: 1.9
  omega_p_max: 1.9
  target_margin:
    - collision_distance
    - evader_bounds_distance
    - pursuer_bounds_distance
  safety_margin:
    - collision
    - evader_bounds
    - pursuer_bounds
  obs_dim: 6
  obsrv_list: &obsrv_list
    ctrl: null
    dstb: null
  reset_criterion: failure

solver:
  device: cuda:0
  rollout_env_device: cuda:0
  num_envs: 1
  num_actors: 2
  num_critics: 1
  # == hyperparameters of learning ==
  max_steps: 15_000_000
  opt_period: 10_000
  num_updates_per_opt: 1_000
  eval_period: 100_000
  min_steps_b4_opt: 100_000
  warmup_steps: 500_000
  batch_size: 256
  ctrl_update_ratio: 2
  warmup_action_range:
    ctrl: *ctrl_range
    dstb: *dstb_range
  memory_capacity: 1_000_000
  softmax_rationality: 3.0
  # == logging ==
  use_wandb: true
  project_name: gameplay-release
  name: isaacs_dubins_2
  max_model: 20
  save_top_k:
    ctrl: 10
    dstb: 10
  out_folder: train_result/isaacs_dubins_2
  eval:   
    b4_learn: true
    metric: safety
    aux_metric: [ep_length, safety]
    num_trajectories: 100
    timeout: 300
    end_criterion: failure
  obs_dim: 6
  obsrv_list: *obsrv_list
  rollout_end_criterion: failure
  # == hyperparameters of actors and critics ==
  critic_0:
    eval: false
    net_name: central
    lr: 0.0001
    lr_schedule: false
    lr_end: 0.0001
    lr_period: 50000
    lr_decay: 0.9
    gamma: 0.9
    gamma_decay: 0.1
    gamma_end: 0.999
    gamma_period: 2_000_000
    gamma_schedule: true
    tau: 0.01
    mode: safety
    terminal_type: all  # use min{l_x, g_x} for terminal states/obsrvs.
    opt_type: AdamW
    update_target_period: 2
  actor_0:
    eval: false
    net_name: ctrl
    actor_type: max
    learn_alpha: true
    lr: 0.0001
    lr_al: 0.000125
    lr_schedule: false
    lr_al_schedule: false
    alpha: 0.1
    min_alpha: 0.001
    opt_type: AdamW
    update_period: 2
    lr_end: 0.0001
    lr_al_end: 0.00005
    lr_period: 50000
    lr_al_period: 100000
    lr_decay: 0.9    
    lr_al_decay: 0.9
  actor_1:
    eval: false
    net_name: dstb
    actor_type: min
    learn_alpha: true
    lr: 0.0001
    lr_al: 0.0000125
    lr_schedule: false
    lr_al_schedule: false
    alpha: 0.1
    min_alpha: 0.001
    opt_type: AdamW
    update_period: 2
    lr_end: 0.0001
    lr_al_end: 0.000005
    lr_period: 50000
    lr_al_period: 100000
    lr_decay: 0.9    
    lr_al_decay: 0.9

arch:
  actor_0:
    mlp_dim:
      - 256
      - 256
      - 256
    activation: Sin
    append_dim: 0
    latent_dim: 0
    obsrv_dim: 6  # [x_e, y_e, theta_e, x_p, y_p, theta_p]
    action_dim: 1  # Continuous actions: [-1.9, 1.9]
    action_range: *ctrl_range
    pretrained_path: /mounted_volume/Gameplay-Filters/train_result/isaacs_dubins/model/ctrl/ctrl-3100000.pth
  actor_1:
    mlp_dim:
      - 256
      - 256
      - 256
    activation: Sin
    append_dim: 0
    latent_dim: 0
    obsrv_dim: 6  # [x_e, y_e, theta_e, x_p, y_p, theta_p]
    action_dim: 1  # Continuous actions: [-1.9, 1.9]
    action_range: *dstb_range
    pretrained_path: /mounted_volume/Gameplay-Filters/train_result/isaacs_dubins/model/dstb/dstb-3100000.pth
  critic_0:
    mlp_dim:
      - 128
      - 128
      - 128
    activation: Sin
    append_dim: 0
    latent_dim: 0
    obsrv_dim: 6  # [x_e, y_e, theta_e, x_p, y_p, theta_p]
    action_dim: 2  # [ctrl_action, dstb_action] - discrete action indices
    pretrained_path: /mounted_volume/Gameplay-Filters/train_result/isaacs_dubins/model/central/central-3100000.pth

eval:
  model_type: [highest, highest] # [ctrl, dstb], highest, safest, worst, manual
  step: [0, 0] # [ctrl, dstb], the step to use if "manual" is chosen for MODEL_TYPE
  eval_timeout: 1000 # how long do we evaluate in real rollout env
  imaginary_horizon: 300 # the horizon of the imaginary env 