environment:
  seed: 0
  # TRACK
  track_len: 20
  track_width_right: .6
  track_width_left: .6
  timeout: 300
  # DONE FLAG PARAM
  end_criterion: failure
  g_x_fail: 0.1
  obs_type: perfect
  obs_spec:
    - [2, -0.4, 0., 0.25, 0.1]
    - [5, 0.4, 0., 0.25, 0.1]
    - [8, 0.1, 0., 0.25, 0.1]
    - [11, -0.1, 0., 0.25, 0.1]
    - [14, -0.4, 0., 0.25, 0.1]
    - [14, 0.4, 0., 0.25, 0.1]
  reset_space:
    - [0., 1.]
    - [-0.6, 0.6]
    - [0.4, 2.0]
    - [-1.5707, 1.5707]
    - [-0.35, 0.35]

cost:
  cost_type: Lagrange
  bidirectional: false
  # CONSTRAINT PARAM
  q1_road: 1.
  q2_road: 10.
  q1_yaw: 1.
  q2_yaw: 10.
  q1_obs: 1.
  q2_obs: 10.
  # COST PARAM
  track_offset: 0.5
  w_vel: 4.
  w_contour: 4.
  w_theta: 0.
  w_accel: 0.01
  w_omega: 0.01
  v_ref: 1.5
  barrier_clip_min: -0.25
  barrier_clip_max: 5.0
  #
  yaw_min: -1.5707
  yaw_max: 1.5707
  has_vel_constr: false
  has_delta_constr: false

agent:
  agent_id: ego
  dyn: BicycleDstb5D
  footprint: Box
  state_box_limit: [0., 0.5, -0.1, 0.1]
  verbose: false
  gui: false
  gui_imaginary: false
  dt: 0.1
  weight : 2.99  # kg
  # CAR DYNAMICS
  wheelbase: 0.257
  num_segment: 10  #! deprecated
  delta_min: -0.35
  delta_max: 0.35
  v_min: 0.4
  v_max: 2.
  action_range:
    ctrl: &ctrl_range
      - [-3.5, 3.5]
      - [-5., 5.]
    dstb: &dstb_range
      - [-0.4, 0.4]
      - [-0.4, 0.4]
      - [-0.4, 0.4]
      - [-0.4, 0.4]
      - [-0.4, 0.4]
  action_type: center_sampling
  action_center:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  target_margin:
    - x_pos
    - y_pos
    - velocity
    - yaw
    - yaw_rate
  safety_margin:
    - road_boundary
    - obstacle_distance
  obs_dim: 5
  obsrv_list: &obsrv_list
    ctrl: null
    dstb: null
  reset_criterion: failure

solver:
  device: cuda
  rollout_env_device: cuda
  num_envs: 1
  num_actors: 2
  num_critics: 1
  # == hyperparameters of learning ==
  max_steps: 20_000_000
  opt_period: 10_000
  num_updates_per_opt: 1_000
  eval_period: 100_000
  min_steps_b4_opt: 100_000
  warmup_steps: 500_000
  batch_size: 256
  ctrl_update_ratio: 2
  warmup_action_range:
    ctrl: *ctrl_range
    dstb: *dstb_range
  memory_capacity: 1_000_000
  softmax_rationality: 3.0
  # == logging ==
  use_wandb: true
  project_name: gameplay-release
  name: isaacs_bicycle
  max_model: 20
  save_top_k:
    ctrl: 10
    dstb: 10
  out_folder: train_result/isaacs_bicycle
  eval:   
    b4_learn: true
    metric: reach-avoid
    aux_metric: [ep_length, safety]
    num_trajectories: 100
    timeout: 300
    end_criterion: reach-avoid
  obs_dim: 5
  obsrv_list:  *obsrv_list
  rollout_end_criterion: reach-avoid
  # == hyperparameters of actors and critics ==
  critic_0:
    eval: false
    net_name: central
    lr: 0.0001
    lr_schedule: false
    lr_end: 0.0001
    lr_period: 50000
    lr_decay: 0.9
    gamma: 0.9
    gamma_decay: 0.1
    gamma_end: 0.999
    gamma_period: 2_000_000
    gamma_schedule: true
    tau: 0.01
    mode: reach-avoid
    terminal_type: all  # use min{l_x, g_x} for terminal states/obsrvs.
    opt_type: AdamW
    update_target_period: 2
  actor_0:
    eval: false
    net_name: ctrl
    actor_type: max
    learn_alpha: true
    lr: 0.0001
    lr_al: 0.000125
    lr_schedule: false
    lr_al_schedule: false
    alpha: 0.1
    min_alpha: 0.001
    opt_type: AdamW
    update_period: 2
    lr_end: 0.0001
    lr_al_end: 0.00005
    lr_period: 50000
    lr_al_period: 100000
    lr_decay: 0.9    
    lr_al_decay: 0.9
  actor_1:
    eval: false
    net_name: dstb
    actor_type: min
    learn_alpha: true
    lr: 0.0001
    lr_al: 0.0000125
    lr_schedule: false
    lr_al_schedule: false
    alpha: 0.1
    min_alpha: 0.001
    opt_type: AdamW
    update_period: 2
    lr_end: 0.0001
    lr_al_end: 0.000005
    lr_period: 50000
    lr_al_period: 100000
    lr_decay: 0.9    
    lr_al_decay: 0.9

arch:
  actor_0:
    mlp_dim:
      - 256
      - 256
      - 256
    activation: Sin
    append_dim: 0
    latent_dim: 0
    obsrv_dim: 5
    action_dim: 2
    action_range: *ctrl_range
    pretrained_path:
  actor_1:
    mlp_dim:
      - 256
      - 256
      - 256
    activation: Sin
    append_dim: 0
    latent_dim: 0
    obsrv_dim: 5
    action_dim: 5
    action_range: *dstb_range
    pretrained_path:
  critic_0:
    mlp_dim:
      - 128
      - 128
      - 128
    activation: Sin
    append_dim: 0
    latent_dim: 0
    obsrv_dim: 5
    action_dim: 7
    pretrained_path:

eval:
  model_type: [highest, highest] # [ctrl, dstb], highest, safest, worst, manual
  step: [0, 0] # [ctrl, dstb], the step to use if "manual" is chosen for MODEL_TYPE
  eval_timeout: 1000 # how long do we evaluate in real rollout env
  imaginary_horizon: 300 # the horizon of the imaginary env
